---
- name: Rm anon user
  mysql_user: name="" state=absent
- name: Rm test DB
  mysql_db: name=test state=absent
- name: Create project DB
  mysql_db: name="{{ database_name }}" state=present
- name: Create project DB user
  mysql_user: name="{{ database_user }}" host=localhost password="{{ database_password }}" priv=Testify.*:ALL

- name: Make executable
  file:
    path: /home/Testify/manage.py
    mode: 0777
- file: src=/usr/bin/python3 dest=/usr/bin/python state=link
- name: Django migrate
  django_manage: command=migrate
                 app_path=/home/Testify
  environment:
    - PATH: "/home/user/.local/bin/:/bin:/usr/bin:/usr/local/bin"

