---
- name: change bind address
  raw: sudo sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/my.cnf 
  

- name: Rm anon user
  mysql_user: name="" state=absent
- name: Rm test DB
  mysql_db: name=test state=absent
- name: Create project DB
  mysql_db: name="{{ database_name }}" state=present
- name: Create project DB user
  mysql_user: name="{{ database_user }}" host=% password="{{ database_password }}" priv=Testify.*:ALL


