---
- hosts: localhost
  connection: local
  become: true
  roles:
    - iliapa.image-download
    - iliapa.ssh
    - iliapa.lxd


- hosts: all
  become: true
  gather_facts: False
  roles:
    - iliapa.python2
    - iliapa.pkgs
    - role: iliapa.clone-rep
      git_repository: https://github.com/iliapa1/Testify.git
    - iliapa.pip-requirements
    - role: iliapa.mariadb
      database_name: Testify
      database_user: Testifyuser
      database_password: bananas

    


  




 



