---
- name: install python
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: check python is installed in container
  raw: dpkg -s python
  register: python_install_check
  failed_when: python_install_check.rc not in [0, 1]
  changed_when: false

- name: install python in container
  raw: apt-get install -y python
  when: python_install_check.rc == 1


- name: change ip
  template:
    src: templates/50-cloud-init.cfg 
    dest: /etc/network/interfaces.d/
    owner: root
    group: root  


