---
- name: Check if ssh exists
  stat: path=/home/.ssh
  register: ssh_present

- name: make ssh folder
  raw: cd /home && mkdir ssh
  when: ssh_present.stat.exists == false

- name: Download ssh key
  raw: cd /home/ssh && wget https://www.dropbox.com/s/3n0nycvm7geqtyw/id_rsa_ansible?dl=1
  when: ssh_present.stat.exists == false
